---
- name: handler test
  hosts: localhost
  tasks:
         - service:
                 name: httpd
                 state: stopped
           notify: start nginx

  handlers:
          - name: start nginx
            service:
             name: nginx
             state: restarted
            
