---
- name: install and start nginx
  hosts: test
  gather_facts: True      
  tasks:
          - name: install nginx
            yum: name=nginx state=present

          - name: service start nginx
            service: name=nginx state=started

          - name: service enable nginx
            service: name=nginx enabled=yes

          - debug:
                  msg: "{{ ansible_os_family }}"
