---
- name: wordpress install
  hosts: web
  vars:
    wp_db: wordpress
    wp_user: wp_user
    wp_pass: wp1234!@#$
    wp_host: 192.168.56.102
  tasks:
    - name: copy WP package
      copy:
         src: wp-latest.tar.gz
         dest: ~/wp-latest.tar.gz

    - name: install httpd
      yum:
         name: httpd,libsemanage-python,php,php-mysql,php-gd,php-pspell
         state: latest

    - name: apache start & enable
      service:
        name: httpd
        state: started
        enabled: yes

    - name: extract wordpress
      unarchive:
        src: /home/devops/wp-latest.tar.gz
        dest: /var/www/html/
        extra_opts: [--strip-components=1]
        remote_src: yes
        owner: apache
        group: apache

    - name: create config file
      template:
        src: wp-config.j2
        dest: /var/www/html/wp-config.php
        owner: apache
        group: apache
        mode: 0644

    - name: Enable Sebool
      seboolean:
        name: httpd_can_network_connect_db
        state: yes
        persistent: yes

    - name: allow firewall http
      firewalld:
       service: http
       permanent: yes
       immediate: true
       state: enabled
